# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dotiw` gem.
# Please instead update this file by running `bin/tapioca gem dotiw`.


# source://dotiw//lib/dotiw/action_view/helpers/date_helper.rb#3
module ActionView
  class << self
    # source://actionview/7.2.1.1/lib/action_view/deprecator.rb#4
    def deprecator; end

    # source://actionview/7.2.1.1/lib/action_view.rb#93
    def eager_load!; end

    # source://actionview/7.2.1.1/lib/action_view/gem_version.rb#5
    def gem_version; end

    # source://actionview/7.2.1.1/lib/action_view/version.rb#7
    def version; end
  end
end

# source://dotiw//lib/dotiw/action_view/helpers/date_helper.rb#4
module ActionView::Helpers
  include ::ActionView::Helpers::SanitizeHelper
  include ::DOTIW::Methods
  include ::ActionView::Helpers::TextHelper
  include ::ActionView::Helpers::UrlHelper
  include ::ActionView::Helpers::SanitizeHelper
  include ::ActionView::Helpers::TextHelper
  include ::ActionView::Helpers::FormTagHelper
  include ::ActionView::Helpers::FormHelper
  include ::ActionView::Helpers::TranslationHelper

  mixes_in_class_methods ::ActionView::Helpers::UrlHelper::ClassMethods
  mixes_in_class_methods ::ActionView::Helpers::SanitizeHelper::ClassMethods

  class << self
    # source://actionview/7.2.1.1/lib/action_view/helpers.rb#35
    def eager_load!; end
  end
end

# source://dotiw//lib/dotiw/action_view/helpers/date_helper.rb#5
module ActionView::Helpers::DateHelper
  include ::DOTIW::Methods

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#95
  def _distance_of_time_in_words(from_time, to_time = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#176
  def _time_ago_in_words(from_time, options = T.unsafe(nil)); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#290
  def date_select(object_name, method, options = T.unsafe(nil), html_options = T.unsafe(nil)); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#366
  def datetime_select(object_name, method, options = T.unsafe(nil), html_options = T.unsafe(nil)); end

  # source://dotiw//lib/dotiw/action_view/helpers/date_helper.rb#25
  def distance_of_time_in_percent(from_time, current_time, to_time, options = T.unsafe(nil)); end

  # source://dotiw//lib/dotiw/action_view/helpers/date_helper.rb#11
  def distance_of_time_in_words(from_time, to_time = T.unsafe(nil), include_seconds_or_options = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://dotiw//lib/dotiw/action_view/helpers/date_helper.rb#18
  def distance_of_time_in_words_to_now(to_time = T.unsafe(nil), include_seconds_or_options = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#454
  def select_date(date = T.unsafe(nil), options = T.unsafe(nil), html_options = T.unsafe(nil)); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#415
  def select_datetime(datetime = T.unsafe(nil), options = T.unsafe(nil), html_options = T.unsafe(nil)); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#597
  def select_day(date, options = T.unsafe(nil), html_options = T.unsafe(nil)); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#570
  def select_hour(datetime, options = T.unsafe(nil), html_options = T.unsafe(nil)); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#541
  def select_minute(datetime, options = T.unsafe(nil), html_options = T.unsafe(nil)); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#642
  def select_month(date, options = T.unsafe(nil), html_options = T.unsafe(nil)); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#517
  def select_second(datetime, options = T.unsafe(nil), html_options = T.unsafe(nil)); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#494
  def select_time(datetime = T.unsafe(nil), options = T.unsafe(nil), html_options = T.unsafe(nil)); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#671
  def select_year(date, options = T.unsafe(nil), html_options = T.unsafe(nil)); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#176
  def time_ago_in_words(from_time, options = T.unsafe(nil)); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#331
  def time_select(object_name, method, options = T.unsafe(nil), html_options = T.unsafe(nil)); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#690
  def time_tag(date_or_time, *args, &block); end

  private

  # source://dotiw//lib/dotiw/action_view/helpers/date_helper.rb#34
  def merge_options(include_seconds_or_options, options); end

  # source://actionview/7.2.1.1/lib/action_view/helpers/date_helper.rb#699
  def normalize_distance_of_time_argument_to_time(value); end
end

# source://dotiw//lib/dotiw.rb#8
module DOTIW
  extend ::ActiveSupport::Autoload
  extend ::DOTIW

  # source://dotiw//lib/dotiw.rb#22
  def init_i18n!; end

  # source://dotiw//lib/dotiw.rb#27
  def languages; end

  # source://dotiw//lib/dotiw.rb#31
  def locale_files; end

  protected

  # source://dotiw//lib/dotiw.rb#37
  def files(directory, ext); end
end

# source://dotiw//lib/dotiw.rb#19
DOTIW::DEFAULT_I18N_SCOPE = T.let(T.unsafe(nil), Symbol)

# source://dotiw//lib/dotiw.rb#20
DOTIW::DEFAULT_I18N_SCOPE_COMPACT = T.let(T.unsafe(nil), Symbol)

# source://dotiw//lib/dotiw/methods.rb#4
module DOTIW::Methods
  extend ::DOTIW::Methods

  # source://dotiw//lib/dotiw/methods.rb#14
  def distance_of_time(seconds, options = T.unsafe(nil)); end

  # @raise [ArgumentError]
  #
  # source://dotiw//lib/dotiw/methods.rb#22
  def distance_of_time_in_words(from_time, to_time = T.unsafe(nil), include_seconds_or_options = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://dotiw//lib/dotiw/methods.rb#7
  def distance_of_time_in_words_hash(from_time, to_time, options = T.unsafe(nil)); end

  # source://dotiw//lib/dotiw/methods.rb#38
  def time_ago_in_words(from_time, include_seconds_or_options = T.unsafe(nil)); end

  private

  # source://dotiw//lib/dotiw/methods.rb#52
  def _display_time_in_words(hash, options = T.unsafe(nil)); end

  # source://dotiw//lib/dotiw/methods.rb#44
  def options_with_scope(options); end
end

# source://dotiw//lib/dotiw/time_hash.rb#4
class DOTIW::TimeHash
  # @return [TimeHash] a new instance of TimeHash
  #
  # source://dotiw//lib/dotiw/time_hash.rb#9
  def initialize(distance, from_time, to_time = T.unsafe(nil), options = T.unsafe(nil)); end

  # Returns the value of attribute distance.
  #
  # source://dotiw//lib/dotiw/time_hash.rb#7
  def distance; end

  # Returns the value of attribute from_time.
  #
  # source://dotiw//lib/dotiw/time_hash.rb#7
  def from_time; end

  # Returns the value of attribute largest.
  #
  # source://dotiw//lib/dotiw/time_hash.rb#7
  def largest; end

  # Returns the value of attribute smallest.
  #
  # source://dotiw//lib/dotiw/time_hash.rb#7
  def smallest; end

  # source://dotiw//lib/dotiw/time_hash.rb#29
  def to_hash; end

  # Returns the value of attribute to_time.
  #
  # source://dotiw//lib/dotiw/time_hash.rb#7
  def to_time; end

  private

  # source://dotiw//lib/dotiw/time_hash.rb#83
  def build_days; end

  # source://dotiw//lib/dotiw/time_hash.rb#79
  def build_hours; end

  # source://dotiw//lib/dotiw/time_hash.rb#75
  def build_minutes; end

  # source://dotiw//lib/dotiw/time_hash.rb#91
  def build_months; end

  # source://dotiw//lib/dotiw/time_hash.rb#70
  def build_seconds; end

  # source://dotiw//lib/dotiw/time_hash.rb#43
  def build_time_hash; end

  # source://dotiw//lib/dotiw/time_hash.rb#87
  def build_weeks; end

  # source://dotiw//lib/dotiw/time_hash.rb#99
  def build_years_months_weeks_days; end

  # Returns the value of attribute options.
  #
  # source://dotiw//lib/dotiw/time_hash.rb#35
  def options; end

  # Returns the value of attribute output.
  #
  # source://dotiw//lib/dotiw/time_hash.rb#35
  def output; end
end

# source://dotiw//lib/dotiw/time_hash.rb#41
DOTIW::TimeHash::FOUR_WEEKS = T.let(T.unsafe(nil), ActiveSupport::Duration)

# source://dotiw//lib/dotiw/time_hash.rb#39
DOTIW::TimeHash::ONE_DAY = T.let(T.unsafe(nil), ActiveSupport::Duration)

# source://dotiw//lib/dotiw/time_hash.rb#38
DOTIW::TimeHash::ONE_HOUR = T.let(T.unsafe(nil), ActiveSupport::Duration)

# source://dotiw//lib/dotiw/time_hash.rb#37
DOTIW::TimeHash::ONE_MINUTE = T.let(T.unsafe(nil), ActiveSupport::Duration)

# source://dotiw//lib/dotiw/time_hash.rb#40
DOTIW::TimeHash::ONE_WEEK = T.let(T.unsafe(nil), ActiveSupport::Duration)

# source://dotiw//lib/dotiw/time_hash.rb#5
DOTIW::TimeHash::TIME_FRACTIONS = T.let(T.unsafe(nil), Array)

# source://dotiw//lib/dotiw/version.rb#4
DOTIW::VERSION = T.let(T.unsafe(nil), String)
