version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      sync-all-versions:
        applies-to: version-updates
        patterns:
          - '@18f/identity-design-system'
          - libphonenumber-js
      sync-major-versions:
        applies-to: version-updates
        patterns:
          - stylelint
        update-types:
          - major
      security:
        applies-to: security-updates
        patterns:
          - '*'
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    groups:
      sync-all-versions:
        applies-to: version-updates
        patterns:
          - phonelib
      security:
        applies-to: security-updates
        patterns:
          - '*'
