engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
        # mass_threshold: 30
      - javascript
    exclude_paths:
    - 'spec/**/*'
    - 'db/schema.rb'
  eslint:
    enabled: true
  fixme:
    enabled: true
    exclude_paths:
    - 'public/build/bundle.js'
  rubocop:
    enabled: true
  scss-lint:
    enabled: true

ratings:
  paths:
  - app/**
  - lib/**
  - '**.rb'
  - '**.go'
