version: "2" # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    enabled: false
  similar-code:
    enabled: false
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    enabled: false
    config:
      threshold: # language-specific defaults. an override will affect all languages.

plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
          mass_threshold: 50
    exclude_patterns:
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'app/forms/password_form.rb'
  fixme:
    enabled: true
    exclude_patterns:
    - 'public/build/bundle.js'
    - '.codeclimate.yml'
    config:
      strings:
      - TODO
      - FIXME
      - HACK
      - BUG
  pep8:
    enabled: true
  reek:
    enabled: false
  scss-lint:
    enabled: true
    checks:
      HexLength:
        enabled: false

exclude_patterns:
  - 'db/schema.rb'
  - 'node_modules/'
  - 'lib/proofer_mocks/'
  - 'lib/tasks/create_test_accounts.rb'
  - 'scripts/load_testing/'
  - 'tmp/'
  - 'config/initializers/jwt.rb'
  - 'spec/support/monitor/monitor_email_helper.rb'
