EnableDefaultLinters: false
linters:
  Rubocop:
    enabled: true
    # There's no special reason for these excludes other than the fact that they have existing
    # issues that haven't been resolved yet. Fix 'em up!
    exclude:
      - '*/app/views/account_reset/*'
      - '*/app/views/accounts/*'
      - '*/app/views/idv/address/*'
      - '*/app/views/idv/come_back_later/*'
      - '*/app/views/idv/confirmations/*'
      - '*/app/views/idv/capture_doc/*'
      - '*/app/views/idv/doc_auth/*'
      - '*/app/views/idv/forgot_password/*'
      - '*/app/views/idv/otp_delivery_method/*'
      - '*/app/views/idv/otp_verification/*'
      - '*/app/views/idv/phone/*'
      - '*/app/views/idv/review/*'
      - '*/app/views/idv/shared/_document_capture.html.erb'
      - '*/app/views/forgot_password/*'
      - '*/app/views/event_disavowal/*'
      - '*/app/views/events/*'
      - '*/app/views/layouts/*'
      - '*/app/views/mfa_confirmation/*'
      - '*/app/views/partials/*'
      - '*/app/views/reactivate_account/*'
      - '*/app/views/saml_idp/*'
      - '*/app/views/service_provider_mfa/*'
      - '*/app/views/session_timeout/*'
      - '*/app/views/shared/*'
      - '*/app/views/sign_up/*'
      - '*/app/views/test/*'
      - '*/app/views/two_factor_authentication/*'
      - '*/app/views/user_mailer/*'
      - '*/app/views/users/*'
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
  DeprecatedClasses:
    enabled: true
    rule_set:
      - deprecated:
          - 'align-(top|middle|bottom|baseline)'
          - '(left)-align'
          - 'justify'
          - 'nowrap'
          - 'line-height-[3]'
          - 'list-style-none'
          - 'table(-cell)?'
          - 'fit'
          - 'max-width-[1-4]'
          - '((sm|md|lg)-)?[mp][trblxy]?(n?[0-6]|-auto)'
          - 'fixed'
          - 'z[1-4]'
          - 'col-(right|[579])'
          - 'sm-col-11?'
          - '(md|lg)-col(-(right|[1-9][0-2]?))?'
          - '(sm|md|lg)-flex'
          - 'flex-(column|none)'
          - '(items|self|justify|content)-(start|end|center|baseline|stretch)'
          - 'order-([0-3]|last)'
          - 'not-rounded'
          - 'rounded-(top|right|bottom|left)'
          - '((sm|md|lg)-)?hide'
          - '(sm|md|lg)-show'
          - 'btn(-(small|big|narrow|wide|link|primary|secondary|danger|disabled|big|narrow|transparent))?'
          - ':not(label).btn-border'
          - 'border-(black|gray|white|aqua|orange|fuchsia|purple|maroon|darken-[1-4]|lighten-[1-4])'
          - 'h3'
        suggestion: 'Use USWDS classes instead of BassCSS.'
      - deprecated:
          - 'js-consent-form'
        suggestion: 'Rename classes that are known to be hidden by the Hush plugin'
  SpaceAroundErbTag:
    enabled: true
