EnableDefaultLinters: false
linters:
  Rubocop:
    enabled: true
    # There's no special reason for these excludes other than the fact that they have existing
    # issues that haven't been resolved yet. Fix 'em up!
    exclude:
      - '*/app/views/account_reset/*'
      - '*/app/views/accounts/_auth_apps.html.erb'
      - '*/app/views/accounts/_backup_codes.html.erb'
      - '*/app/views/accounts/_connected_app.html.erb'
      - '*/app/views/accounts/_emails.html.erb'
      - '*/app/views/accounts/_identity_item.html.erb'
      - '*/app/views/accounts/_password_reset.html.erb'
      - '*/app/views/accounts/_pending_profile_bounced_gpo.html.erb'
      - '*/app/views/accounts/_pending_profile_gpo.html.erb'
      - '*/app/views/accounts/_personal_key.html.erb'
      - '*/app/views/accounts/_phone.html.erb'
      - '*/app/views/accounts/_piv_cac.html.erb'
      - '*/app/views/accounts/_webauthn.html.erb'
      - '*/app/views/accounts/actions/_manage_personal_key.html.erb'
      - '*/app/views/accounts/show.html.erb'
      - '*/app/views/idv/confirmations/*'
      - '*/app/views/idv/capture_doc/*'
      - '*/app/views/idv/doc_auth/_back.html.erb'
      - '*/app/views/idv/doc_auth/_error_messages.html.erb'
      - '*/app/views/idv/doc_auth/_ssn_init.html.erb'
      - '*/app/views/idv/doc_auth/_ssn_update.html.erb'
      - '*/app/views/idv/doc_auth/agreement.html.erb'
      - '*/app/views/idv/doc_auth/document_capture.html.erb'
      - '*/app/views/idv/doc_auth/link_sent.html.erb'
      - '*/app/views/idv/doc_auth/no_camera.html.erb'
      - '*/app/views/idv/doc_auth/upload.html.erb'
      - '*/app/views/idv/doc_auth/send_link.html.erb'
      - '*/app/views/idv/doc_auth/verify.html.erb'
      - '*/app/views/idv/doc_auth/verify_wait.html.erb'
      - '*/app/views/idv/phone/new.html.erb'
      - '*/app/views/idv/shared/_document_capture.html.erb'
      - '*/app/views/event_disavowal/*'
      - '*/app/views/mfa_confirmation/*'
      - '*/app/views/reactivate_account/*'
      - '*/app/views/session_timeout/*'
      - '*/app/views/shared/*'
      - '*/app/views/two_factor_authentication/*'
      - '*/app/views/user_mailer/*'
      - '*/app/views/users/authorization_confirmation/*'
      - '*/app/views/users/backup_code_setup/*'
      - '*/app/views/users/delete/*'
      - '*/app/views/users/edit_phone/*'
      - '*/app/views/users/email_language/*'
      - '*/app/views/users/emails/*'
      - '*/app/views/users/passwords/*'
      - '*/app/views/users/phone_setup/*'
      - '*/app/views/users/phones/*'
      - '*/app/views/users/piv_cac_setup/*'
      - '*/app/views/users/piv_cac_setup_from_sign_in/*'
      - '*/app/views/users/rules_of_use/*'
      - '*/app/views/users/service_provider_inactive/*'
      - '*/app/views/users/service_provider_revoke/*'
      - '*/app/views/users/shared/_otp_delivery_preference_selection.html.erb'
      - '*/app/views/users/shared/_otp_make_default_number.html.erb'
      - '*/app/views/users/shared/_phone_number_edit.html.erb'
      - '*/app/views/users/totp_setup/*'
      - '*/app/views/users/two_factor_authentication_setup/*'
      - '*/app/views/users/verify_password/*'
      - '*/app/views/users/verify_personal_key/*'
      - '*/app/views/users/webauthn_setup/*'
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
  DeprecatedClasses:
    enabled: true
    rule_set:
      - deprecated:
          - (black|silver|white|aqua|blue|navy|teal|green|olive|lime|yellow|orange|red|fuchsia|purple|maroon|color-inherit|muted)
          - 'align-(top|middle|bottom|baseline)'
          - '(left)-align'
          - 'justify'
          - 'nowrap'
          - 'line-height-[3]'
          - 'list-style-none'
          - 'table(-cell)?'
          - 'fit'
          - 'max-width-[1-4]'
          - '((sm|md|lg)-)?[mp][trblxy]?(n?[0-6]|-auto)'
          - 'fixed'
          - 'z[1-4]'
          - 'col-(right|[579])'
          - 'sm-col-11?'
          - '(md|lg)-col(-(right|[1-9][0-2]?))?'
          - '(sm|md|lg)-flex'
          - 'hljs'
          - 'range-light'
          - 'field-dark'
          - 'progress'
          - 'flex-(column|none)'
          - '((sm|md|lg)-)?table(-(cell|fixed))?'
          - '[xy]-group-item'
          - '(items|self|justify|content)-(start|end|center|baseline|stretch)'
          - 'order-([0-3]|last)'
          - 'circle'
          - '(not-)?rounded(-(top|right|bottom|left|lg))?'
          - '((sm|md|lg)-)?hide'
          - '(sm|md|lg)-show'
          - 'btn(-(small|big|narrow|wide|link|primary|secondary|danger|disabled|big|narrow|transparent|border))?'
          - '(border|bg)-(none|black|gray|silver|aqua|blue|navy|teal|green|olive|lime|orange|red|fuchsia|purple|maroon|darken-[1-4]|lighten-[1-4])'
          - 'bg-(cover|contain|center|top|right|bottom|left)'
          - 'h([03]|00)'
          - 'h([01]|00)-responsive'
        suggestion: 'Use USWDS classes instead of BassCSS.'
      - deprecated:
          - 'js-consent-form'
        suggestion: 'Rename classes that are known to be hidden by the Hush plugin'
  SpaceAroundErbTag:
    enabled: true
