EnableDefaultLinters: false
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
  DeprecatedClasses:
    enabled: true
    rule_set:
      - deprecated:
          - 'js-consent-form'
        suggestion: 'Rename classes that are known to be hidden by the Hush plugin'
  SpaceAroundErbTag:
    enabled: true
  CommentSyntax:
    enabled: true
