devenv-test:
  image: $ECR_REGISTRY/github/cachix/devenv/devenv:v1.10
  script:
    - devenv test
  needs: []
  # We are caching built binaries from devenv in s3 to reduce execution time per job.
  tags:
    - build-pool
  rules:
    - !reference [.merge_request, rules]
    - changes:
      - .ruby-version
      - .gitlab-ci-devenv.yml
      - devenv.*
