scss_files:
  - 'app/assets/stylesheets/**'
  - 'app/javascript/**'

exclude:
  - 'vendor/assets/stylesheets/**'
  - 'node_modules/**'

linters:
  HexLength:
    enabled: false
  ColorVariable:
    enabled: false
  SelectorFormat:
    convention: hyphenated_BEM
