gem:
  # Add your `gem` command parameters here:
  # doc: true
  workers: 1
  exclude:
#    - ast
    - axe-core-api
    - axe-core-rspec
    - axiom-types
    - benchmark-ips
    - better_errors
    - better_html
    - brakeman
#    - bullet
#    - bundler-audit
    - byebug
#    - capybara
    - capybara-webmock
    - coderay
    - coercible
    - crack
    - dead_end
    - derailed_benchmarks
    - descendants_tracker
    - diff-lcs
    - docile
    - dumb_delegator
    - email_spec
    - erb_lint
#    - factory_bot
#    - factory_bot_rails
    - get_process_mem
    - google-protobuf
    - hashdiff
    - heapy
    - highline
    - i18n-tasks
    - ice_nine
    - json
    - knapsack
    - language_server-protocol
    - launchy
    - letter_opener
    - listen
    - matrix
    - memory_profiler
    - mini_histogram
#    - net-http-persistent
    - netrc
    - parallel
    - parser
#    - pg_query
    - prism
    - pry
    - pry-byebug
    - pry-doc
    - pry-rails
#    - rack-mini-profiler
    - rack-proxy
#    - rack_session_access
    - rails-controller-testing
#    - rails-i18n
    - rainbow
    - rb-fsevent
    - rb-inotify
    - rbi
    - regexp_parser
    - rspec
    - rspec-core
    - rspec-expectations
    - rspec-mocks
    - rspec-rails
    - rspec-retry
    - rspec-support
    - rspec_junit_formatter
    - rubocop
    - rubocop-ast
    - rubocop-factory_bot
    - rubocop-performance
    - rubocop-rails
    - rubocop-rspec
    - rubocop-rspec_rails
    - rubocop-sorbet
    - rubocop-thread_safety
    - rubocop-yard
    - ruby-lsp
    - ruby-lsp-rails
    - ruby-lsp-rspec
    - ruby-statistics
    - selenium-webdriver
    - shoulda-matchers
    - simple_xlsx_reader
    - simplecov
    - simplecov-cobertura
    - simplecov-html
    - simplecov_json_formatter
    - smart_properties
    - solargraph
    - sorbet
    - sorbet-runtime
    - sorbet-static
    - spoom
#    - sqlite3
    - tableparser
    - tapioca
    - thread_safe
    - uniform_notifier
    - virtus
    - webmock
    - websocket
#    - xpath
    - yard-sorbet
    - zonebie
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  workers: 1
