gem:
  # Add your `gem` command parameters here:
  #
  # exclude:
  # - gem_name
  # doc: true
   workers: 1
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
   workers: 1
   verify: true
