# typed: true
# frozen_string_literal: true

# Add the lib directory to the $LOAD_PATH explicitly using a relative path
lib_path = File.expand_path('../../../lib', __FILE__)
$LOAD_PATH.unshift(lib_path)

# require './lib/cleanup/destroy_unused_providers'
# require './lib/cleanup/destroyable_records'
# require './spec/simplecov_helper'
# require './spec/support/oidc_auth_helper'
# require './spec/support/saml_auth_helper'
# require 'action_controller/railtie'
# require 'action_mailer/railtie'
# require 'action_view/railtie'
# require 'active_job/log_subscriber'
# require 'active_record/railtie'
# require 'active_support'
# require 'active_support/core_ext/hash/deep_merge'
# require 'active_support/core_ext/hash/except'
# require 'active_support/core_ext/object/blank'
# require 'active_support/core_ext/string/filters'
require 'rails/all'
# require 'aws-sdk-cloudwatchlogs'
# require 'aws-sdk-pinpoint'
# require 'aws-sdk-pinpointsmsvoice'
# require 'aws-sdk-s3'
# require 'aws/ses'
# require 'axe-rspec'
require 'barby'
require 'barby/barcode/code_128'
# require 'barby/outputter/html_outputter'
# require 'barby/outputter/png_outputter'
# require 'base64'
# require 'bootsnap/setup'
# require 'browser/aliases'
# require 'bundler/setup'
require 'browser'
# require 'capybara/rspec'
# require 'capybara/webmock'
# require 'caxlsx'
# require 'cgi'
# require 'concurrent-ruby'
# require 'csv'
# require 'data_requests/deployed'
# require 'data_requests/deployed/create_email_addresses_report'
# require 'data_requests/deployed/create_mfa_configurations_report'
# require 'data_requests/deployed/create_user_events_report'
# require 'data_requests/deployed/create_user_report'
# require 'data_requests/deployed/lookup_shared_device_users'
# require 'data_requests/deployed/lookup_user_by_uuid'
# require 'data_requests/local'
# require 'data_requests/local/fetch_cloudwatch_logs'
# require 'data_requests/local/write_cloudwatch_logs'
# require 'data_requests/local/write_user_events'
# require 'data_requests/local/write_user_info'
# require 'date'
# require 'deploy/migration_statement_timeout'
# require 'devise/orm/active_record'
# require 'digest'
# require 'email_spec'
# require 'email_spec/rspec'
# require 'erb'
# require 'extensions/capybara/node/simple'
require 'extensions/simple_form/active_view_extensions/form_helper'
require 'extensions/simple_form/components/html5_no_aria_required'
require 'extensions/simple_form/components/submit_component'
require 'extensions/simple_form/error_notification'
# require 'fileutils'
# require 'forwardable'
# require 'fugit'
# require 'i18n'
# require 'i18n/tasks'
require 'identity/hostdata'
require 'identity_validations'
require 'idp/constants'
# require 'ipaddr'
require 'jwt'
# require 'knapsack'
# require 'lookbook'
# require 'net/http/persistent'
# require 'new_relic/agent/method_tracer'
# require 'nokogiri'
# require 'open3'
# require 'openssl'
# require 'optparse'
# require 'ostruct'
# require 'pg_query'
# require 'piv_cac/check_config'
# require 'prometheus_exporter/middleware'
# require 'rack-mini-profiler'
# require 'rack/headers_filter'
# require 'rack/timeout/base'
# require 'rack_session_access/capybara'
# require 'rails/test_unit/railtie'
# require 'rake'
require 'reporting/authentication_report'
require 'reporting/cloudwatch_client'
require 'reporting/cloudwatch_query_quoting'
require 'reporting/cloudwatch_query_time_slice'
require 'reporting/command_line_options'
require 'reporting/drop_off_report'
require 'reporting/fraud_metrics_lg99_report'
require 'reporting/identity_verification_report'
require 'reporting/mfa_report'
require 'reporting/monthly_idv_report'
require 'reporting/proofing_rate_report'
require 'reporting/protocols_report'
require 'reporting/unknown_progress_bar'
# require 'resolv'
# require 'retries'
# require 'rexml/document'
# require 'rexml/xpath'
# require 'rspec/matchers/built_in/count_expectation'
# require 'rspec/rails'
# require 'rubocop'
# require 'rubocop/rspec/cop_helper'
# require 'rubocop/rspec/expect_offense'
# require 'ruby-progressbar'
# require 'ruby-progressbar/outputs/null'
# require 'saml_idp/logout_request_builder'
# require 'saml_idp/logout_response_builder'
# require 'securerandom'
# require 'selenium/webdriver'
# require 'shoulda/matchers'
# require 'simple_xlsx_reader'
# require 'simplecov-cobertura'
# require 'simplecov-html'
# require 'simplecov/no_defaults'
# require 'simplecov_json_formatter'
# require 'socket'
# require 'sqlite3'
# require 'stringex/core_ext'
# require 'stringex/unidecoder'
# require 'stringio'
# require 'support/flow_policy_helper'
# require 'tableparser'
# require 'telephony/alert_sender'
# require 'telephony/configuration'
# require 'telephony/errors'
# require 'telephony/otp_sender'
# require 'telephony/phone_number_info'
# require 'telephony/pinpoint/aws_credential_builder'
# require 'telephony/pinpoint/opt_out_manager'
# require 'telephony/pinpoint/pinpoint_helper'
# require 'telephony/pinpoint/sms_sender'
# require 'telephony/pinpoint/voice_sender'
# require 'telephony/response'
# require 'telephony/test/call'
# require 'telephony/test/error_simulator'
# require 'telephony/test/message'
# require 'telephony/test/sms_sender'
# require 'telephony/test/voice_sender'
# require 'telephony/util'
# require 'tempfile'
# require 'terminal-table'
# require 'time'
# require 'tmpdir'
# require 'view_component/test_helpers'
# require 'webmock/rspec'
# require 'xmldsig'
# require 'yaml'
# require 'yard'
# require 'zlib'
# require 'zonebie'
# require 'zonebie/rspec'
require 'uri'
