# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PushNotification::HttpPush`.
# Please instead update this file by running `bin/tapioca dsl PushNotification::HttpPush`.


class PushNotification::HttpPush
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
