{{- if .Values.redis.enabled }}
# templates/redis/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "identity-idp-chart.redis.fullname" . }}
  labels:
    {{- include "identity-idp-chart.redis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "identity-idp-chart.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "identity-idp-chart.redis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}:{{ .Values.redis.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_USERNAME
              value: {{ .Values.redis.username }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
{{- end }}
