#!/bin/bash

# This script is called by identity-devops cookbooks as part of the deployment
# process. It fetches the latest application.yml from S3 to ensure the app is
# properly configured.

set -euo pipefail

echo "deploy/activate starting"
echo "HOME: ${HOME-}"
cd "$(dirname "$0")/.."

set -x

id
which bundle

bundle exec bin/activate

set +x

echo "deploy/activate finished"
