module ActionController
  module AllowBrowser
    extend ActiveSupport::Concern

    module ClassMethods
      def allow_browser: (versions: :modern | Hash[untyped, false | _ToS], ?block: ^() [self: Base] -> void, **untyped options) -> void
    end
  end

  class Base < Metal
    extend AllowBrowser::ClassMethods
  end
end

