module DocPiiHelper
  def pii_like_keypaths_state_id
    [
      [:pii],
      [:errors, :name],
      [:error_details, :name],
      [:error_details, :name, :name],
      [:errors, :dob],
      [:error_details, :dob],
      [:error_details, :dob, :dob],
      [:errors, :dob_min_age],
      [:error_details, :dob_min_age],
      [:error_details, :dob_min_age, :dob_min_age],
      [:errors, :address1],
      [:error_details, :address1],
      [:error_details, :address1, :address1],
      [:errors, :state],
      [:error_details, :state],
      [:error_details, :state, :state],
      [:errors, :zipcode],
      [:error_details, :zipcode],
      [:error_details, :zipcode, :zipcode],
      [:errors, :jurisdiction],
      [:error_details, :jurisdiction],
      [:error_details, :jurisdiction, :jurisdiction],
      [:errors, :state_id_number],
      [:error_details, :state_id_number],
      [:error_details, :state_id_number, :state_id_number],
    ]
  end

  def pii_like_keypaths_passport
    [
      [:pii],
      [:errors, :name],
      [:error_details, :name],
      [:error_details, :name, :name],
      [:errors, :dob],
      [:error_details, :dob],
      [:error_details, :dob, :dob],
      [:errors, :dob_min_age],
      [:error_details, :dob_min_age],
      [:error_details, :dob_min_age, :dob_min_age],
      [:errors, :birth_place],
      [:error_details, :birth_place],
      [:error_details, :birth_place, :birth_place],
      [:errors, :passport_issued],
      [:error_details, :passport_issued],
      [:error_details, :passport_issued, :passport_issued],
      [:errors, :issuing_country_code],
      [:error_details, :issuing_country_code],
      [:error_details, :issuing_country_code, :issuing_country_code],
      [:errors, :nationality_code],
      [:error_details, :nationality_code],
      [:error_details, :nationality_code, :nationality_code],
      [:errors, :mrz],
      [:error_details, :mrz],
      [:error_details, :mrz, :mrz],
    ]
  end
end
