---
AD:
  country_code: '376'
  name: Andorra
  supports_sms: true
  supports_voice: false
AE:
  country_code: '971'
  name: United Arab Emirates (UAE)
  supports_sms: false
  supports_voice: false
AF:
  country_code: '93'
  name: Afghanistan
  supports_sms: true
  supports_voice: false
AG:
  country_code: '1268'
  name: Antigua and Barbuda
  supports_sms: true
  supports_voice: false
AI:
  country_code: '1264'
  name: Anguilla
  supports_sms: true
  supports_voice: false
AL:
  country_code: '355'
  name: Albania
  supports_sms: true
  supports_voice: false
AM:
  country_code: '374'
  name: Armenia
  supports_sms: true
  supports_voice: false
AR:
  country_code: '54'
  name: Argentina
  supports_sms: true
  supports_voice: true
AT:
  country_code: '43'
  name: Austria
  supports_sms: true
  supports_voice: true
AU:
  country_code: '61'
  name: Australia
  supports_sms: true
  supports_voice: true
AW:
  country_code: '297'
  name: Aruba
  supports_sms: true
  supports_voice: false
AZ:
  country_code: '994'
  name: Azerbaijan
  supports_sms: true
  supports_voice: false
BA:
  country_code: '387'
  name: Bosnia and Herzegovina
  supports_sms: true
  supports_voice: false
BB:
  country_code: '1246'
  name: Barbados
  supports_sms: true
  supports_voice: true
BD:
  country_code: '880'
  name: Bangladesh
  supports_sms: true
  supports_voice: false
BE:
  country_code: '32'
  name: Belgium
  supports_sms: true
  supports_voice: false
BF:
  country_code: '226'
  name: Burkina Faso
  supports_sms: true
  supports_voice: true
BG:
  country_code: '359'
  name: Bulgaria
  supports_sms: true
  supports_voice: true
BH:
  country_code: '973'
  name: Bahrain
  supports_sms: true
  supports_voice: true
BI:
  country_code: '257'
  name: Burundi
  supports_sms: true
  supports_voice: false
BM:
  country_code: '1441'
  name: Bermuda
  supports_sms: true
  supports_voice: false
BN:
  country_code: '673'
  name: Brunei
  supports_sms: true
  supports_voice: false
BO:
  country_code: '591'
  name: Bolivia
  supports_sms: true
  supports_voice: false
BQ:
  country_code: '599'
  name: Netherlands Antilles
  supports_sms: true
  supports_voice: false
BR:
  country_code: '55'
  name: Brazil
  supports_sms: true
  supports_voice: true
BS:
  country_code: '1242'
  name: Bahamas
  supports_sms: true
  supports_voice: false
BT:
  country_code: '975'
  name: Bhutan
  supports_sms: true
  supports_voice: false
BW:
  country_code: '267'
  name: Botswana
  supports_sms: true
  supports_voice: false
BY:
  country_code: '375'
  name: Belarus
  supports_sms: true
  supports_voice: false
BZ:
  country_code: '501'
  name: Belize
  supports_sms: true
  supports_voice: false
CA:
  country_code: '1'
  name: Canada
  supports_sms: true
  supports_voice: true
CD:
  country_code: '243'
  name: Democratic Republic of the Congo
  supports_sms: true
  supports_voice: false
CF:
  country_code: '236'
  name: Central African Republic
  supports_sms: true
  supports_voice: false
CG:
  country_code: '242'
  name: Republic of the Congo
  supports_sms: true
  supports_voice: false
CH:
  country_code: '41'
  name: Switzerland
  supports_sms: true
  supports_voice: true
CI:
  country_code: '225'
  name: Ivory Coast
  supports_sms: true
  supports_voice: false
CK:
  country_code: '682'
  name: Cook Islands
  supports_sms: true
  supports_voice: false
CL:
  country_code: '56'
  name: Chile
  supports_sms: true
  supports_voice: true
CM:
  country_code: '237'
  name: Cameroon
  supports_sms: true
  supports_voice: false
CN:
  country_code: '86'
  name: China
  supports_sms: true
  supports_voice: false
CO:
  country_code: '57'
  name: Colombia
  supports_sms: true
  supports_voice: true
CR:
  country_code: '506'
  name: Costa Rica
  supports_sms: true
  supports_voice: false
CV:
  country_code: '238'
  name: Cape Verde
  supports_sms: true
  supports_voice: false
CY:
  country_code: '357'
  name: Cyprus
  supports_sms: true
  supports_voice: true
CZ:
  country_code: '420'
  name: Czechia (Czech Republic)
  supports_sms: true
  supports_voice: false
DE:
  country_code: '49'
  name: Germany
  supports_sms: true
  supports_voice: true
DJ:
  country_code: '253'
  name: Djibouti
  supports_sms: true
  supports_voice: false
DK:
  country_code: '45'
  name: Denmark
  supports_sms: true
  supports_voice: false
DM:
  country_code: '1767'
  name: Dominica
  supports_sms: true
  supports_voice: false
DO:
  country_code: '1'
  name: Dominican Republic
  supports_sms: true
  supports_voice: true
DZ:
  country_code: '213'
  name: Algeria
  supports_sms: true
  supports_voice: false
EC:
  country_code: '593'
  name: Ecuador
  supports_sms: true
  supports_voice: true
EE:
  country_code: '372'
  name: Estonia
  supports_sms: true
  supports_voice: false
EG:
  country_code: '20'
  name: Egypt
  supports_sms: true
  supports_voice: false
ER:
  country_code: '291'
  name: Eritrea
  supports_sms: true
  supports_voice: false
ES:
  country_code: '34'
  name: Spain
  supports_sms: true
  supports_voice: false
ET:
  country_code: '251'
  name: Ethiopia
  supports_sms: true
  supports_voice: false
FI:
  country_code: '358'
  name: Finland
  supports_sms: true
  supports_voice: true
FJ:
  country_code: '679'
  name: Fiji
  supports_sms: true
  supports_voice: false
FM:
  country_code: '691'
  name: Micronesia (Federated States of)
  supports_sms: true
  supports_voice: false
FO:
  country_code: '298'
  name: Faroe Islands
  supports_sms: true
  supports_voice: false
FR:
  country_code: '33'
  name: France
  supports_sms: true
  supports_voice: false
GA:
  country_code: '241'
  name: Gabon
  supports_sms: true
  supports_voice: false
GB:
  country_code: '44'
  name: United Kingdom
  supports_sms: true
  supports_voice: true
GD:
  country_code: '1473'
  name: Grenada
  supports_sms: true
  supports_voice: true
GE:
  country_code: '995'
  name: Georgia
  supports_sms: true
  supports_voice: false
GF:
  country_code: '594'
  name: French Guiana
  supports_sms: true
  supports_voice: false
GG:
  country_code: '44'
  name: Guernsey
  supports_sms: true
  supports_voice: false
GH:
  country_code: '233'
  name: Ghana
  supports_sms: true
  supports_voice: false
GI:
  country_code: '350'
  name: Gibraltar
  supports_sms: true
  supports_voice: false
GL:
  country_code: '299'
  name: Greenland
  supports_sms: true
  supports_voice: false
GM:
  country_code: '220'
  name: Gambia
  supports_sms: true
  supports_voice: false
GN:
  country_code: '224'
  name: Guinea
  supports_sms: true
  supports_voice: false
GP:
  country_code: '590'
  name: Guadeloupe
  supports_sms: true
  supports_voice: false
GQ:
  country_code: '240'
  name: Equitorial Guinea
  supports_sms: true
  supports_voice: false
GR:
  country_code: '30'
  name: Greece
  supports_sms: true
  supports_voice: true
GT:
  country_code: '502'
  name: Guatemala
  supports_sms: true
  supports_voice: true
GU:
  country_code: '1671'
  name: Guam
  supports_sms: true
  supports_voice: false
GW:
  country_code: '245'
  name: Guinea-Bissau
  supports_sms: true
  supports_voice: false
GY:
  country_code: '592'
  name: Guyana
  supports_sms: true
  supports_voice: false
HK:
  country_code: '852'
  name: Hong Kong
  supports_sms: true
  supports_voice: false
HN:
  country_code: '504'
  name: Honduras
  supports_sms: true
  supports_voice: false
HR:
  country_code: '385'
  name: Croatia
  supports_sms: true
  supports_voice: true
HT:
  country_code: '509'
  name: Haiti
  supports_sms: true
  supports_voice: false
HU:
  country_code: '36'
  name: Hungary
  supports_sms: true
  supports_voice: true
ID:
  country_code: '62'
  name: Indonesia
  supports_sms: true
  supports_voice: true
IE:
  country_code: '353'
  name: Ireland
  supports_sms: true
  supports_voice: true
IL:
  country_code: '972'
  name: Israel
  supports_sms: true
  supports_voice: true
IM:
  country_code: '44'
  name: Isle of Man
  supports_sms: true
  supports_voice: false
IN:
  country_code: '91'
  name: India
  supports_sms: true
  supports_voice: false
IQ:
  country_code: '964'
  name: Iraq
  supports_sms: true
  supports_voice: false
IS:
  country_code: '354'
  name: Iceland
  supports_sms: true
  supports_voice: true
IT:
  country_code: '39'
  name: Italy
  supports_sms: true
  supports_voice: true
JE:
  country_code: '44'
  name: Jersey
  supports_sms: true
  supports_voice: false
JM:
  country_code: '1'
  name: Jamaica
  supports_sms: true
  supports_voice: true
JO:
  country_code: '962'
  name: Jordan
  supports_sms: true
  supports_voice: false
JP:
  country_code: '81'
  name: Japan
  supports_sms: true
  supports_voice: false
KE:
  country_code: '254'
  name: Kenya
  supports_sms: true
  supports_voice: true
KG:
  country_code: '996'
  name: Kyrgyzstan
  supports_sms: true
  supports_voice: false
KH:
  country_code: '855'
  name: Cambodia
  supports_sms: true
  supports_voice: true
KM:
  country_code: '269'
  name: Comoros
  supports_sms: true
  supports_voice: false
KN:
  country_code: '1869'
  name: Saint Kitts and Nevis
  supports_sms: true
  supports_voice: false
KR:
  country_code: '82'
  name: South Korea
  supports_sms: true
  supports_voice: false
KW:
  country_code: '965'
  name: Kuwait
  supports_sms: false
  supports_voice: false
KY:
  country_code: '1345'
  name: Cayman Islands
  supports_sms: true
  supports_voice: true
KZ:
  country_code: '7'
  name: Kazakhstan
  supports_sms: true
  supports_voice: true
LA:
  country_code: '856'
  name: Laos
  supports_sms: true
  supports_voice: false
LB:
  country_code: '961'
  name: Lebanon
  supports_sms: true
  supports_voice: false
LC:
  country_code: '1758'
  name: Saint Lucia
  supports_sms: true
  supports_voice: false
LI:
  country_code: '423'
  name: Liechtenstein
  supports_sms: true
  supports_voice: false
LK:
  country_code: '94'
  name: Sri Lanka
  supports_sms: false
  supports_voice: false
LR:
  country_code: '231'
  name: Liberia
  supports_sms: true
  supports_voice: false
LS:
  country_code: '266'
  name: Lesotho
  supports_sms: true
  supports_voice: false
LT:
  country_code: '370'
  name: Lithuania
  supports_sms: true
  supports_voice: true
LU:
  country_code: '352'
  name: Luxembourg
  supports_sms: true
  supports_voice: true
LV:
  country_code: '371'
  name: Latvia
  supports_sms: true
  supports_voice: true
LY:
  country_code: '218'
  name: Libya
  supports_sms: true
  supports_voice: false
MA:
  country_code: '212'
  name: Morocco
  supports_sms: true
  supports_voice: false
MC:
  country_code: '377'
  name: Monaco
  supports_sms: true
  supports_voice: false
MD:
  country_code: '373'
  name: Moldova
  supports_sms: true
  supports_voice: true
ME:
  country_code: '382'
  name: Montenegro
  supports_sms: true
  supports_voice: false
MG:
  country_code: '261'
  name: Madagascar
  supports_sms: true
  supports_voice: false
MH:
  country_code: '692'
  name: Marshall Islands, The
  supports_sms: true
  supports_voice: false
MK:
  country_code: '389'
  name: Macedonia
  supports_sms: true
  supports_voice: false
ML:
  country_code: '223'
  name: Mali
  supports_sms: true
  supports_voice: true
MM:
  country_code: '95'
  name: Myanmar
  supports_sms: true
  supports_voice: false
MN:
  country_code: '976'
  name: Mongolia
  supports_sms: true
  supports_voice: false
MO:
  country_code: '853'
  name: Macau
  supports_sms: true
  supports_voice: false
MQ:
  country_code: '596'
  name: Martinique
  supports_sms: true
  supports_voice: false
MR:
  country_code: '222'
  name: Mauritania
  supports_sms: true
  supports_voice: false
MS:
  country_code: '1664'
  name: Montserrat
  supports_sms: true
  supports_voice: false
MT:
  country_code: '356'
  name: Malta
  supports_sms: true
  supports_voice: false
MU:
  country_code: '230'
  name: Mauritius
  supports_sms: true
  supports_voice: false
MV:
  country_code: '960'
  name: Maldives
  supports_sms: true
  supports_voice: false
MW:
  country_code: '265'
  name: Malawi
  supports_sms: true
  supports_voice: false
MX:
  country_code: '52'
  name: Mexico
  supports_sms: true
  supports_voice: true
MY:
  country_code: '60'
  name: Malaysia
  supports_sms: true
  supports_voice: false
MZ:
  country_code: '258'
  name: Mozambique
  supports_sms: true
  supports_voice: false
NA:
  country_code: '264'
  name: Namibia
  supports_sms: true
  supports_voice: false
NC:
  country_code: '687'
  name: New Caledonia
  supports_sms: true
  supports_voice: false
NE:
  country_code: '227'
  name: Niger
  supports_sms: true
  supports_voice: false
NG:
  country_code: '234'
  name: Nigeria
  supports_sms: true
  supports_voice: false
NI:
  country_code: '505'
  name: Nicaragua
  supports_sms: true
  supports_voice: true
NL:
  country_code: '31'
  name: Netherlands
  supports_sms: true
  supports_voice: false
'NO':
  country_code: '47'
  name: Norway
  supports_sms: true
  supports_voice: true
NP:
  country_code: '977'
  name: Nepal
  supports_sms: true
  supports_voice: false
NU:
  country_code: '683'
  name: Niue
  supports_sms: true
  supports_voice: false
NZ:
  country_code: '64'
  name: New Zealand
  supports_sms: true
  supports_voice: true
OM:
  country_code: '968'
  name: Oman
  supports_sms: true
  supports_voice: false
PA:
  country_code: '507'
  name: Panama
  supports_sms: true
  supports_voice: true
PE:
  country_code: '51'
  name: Peru
  supports_sms: true
  supports_voice: true
PF:
  country_code: '689'
  name: French Polynesia
  supports_sms: true
  supports_voice: false
PG:
  country_code: '675'
  name: Papua New Guinea
  supports_sms: true
  supports_voice: false
PH:
  country_code: '63'
  name: Philippines
  supports_sms: true
  supports_voice: true
PK:
  country_code: '92'
  name: Pakistan
  supports_sms: true
  supports_voice: false
PL:
  country_code: '48'
  name: Poland
  supports_sms: true
  supports_voice: true
PR:
  country_code: '1'
  name: Puerto Rico
  supports_sms: true
  supports_voice: true
PS:
  country_code: '970'
  name: Palestine
  supports_sms: true
  supports_voice: false
PT:
  country_code: '351'
  name: Portugal
  supports_sms: true
  supports_voice: false
PY:
  country_code: '595'
  name: Paraguay
  supports_sms: true
  supports_voice: false
QA:
  country_code: '974'
  name: Qatar
  supports_sms: false
  supports_voice: false
RE:
  country_code: '262'
  name: Réunion (France)
  supports_sms: true
  supports_voice: false
RO:
  country_code: '40'
  name: Romania
  supports_sms: true
  supports_voice: true
RS:
  country_code: '381'
  name: Serbia
  supports_sms: true
  supports_voice: false
RU:
  country_code: '7'
  name: Russia
  supports_sms: false
  supports_voice: false
RW:
  country_code: '250'
  name: Rwanda
  supports_sms: true
  supports_voice: false
SA:
  country_code: '966'
  name: Saudi Arabia
  supports_sms: false
  supports_voice: false
SB:
  country_code: '677'
  name: Solomon Islands
  supports_sms: true
  supports_voice: false
SC:
  country_code: '248'
  name: Seychelles
  supports_sms: true
  supports_voice: false
SE:
  country_code: '46'
  name: Sweden
  supports_sms: true
  supports_voice: false
SG:
  country_code: '65'
  name: Singapore
  supports_sms: true
  supports_voice: false
SI:
  country_code: '386'
  name: Slovenia
  supports_sms: true
  supports_voice: true
SK:
  country_code: '421'
  name: Slovakia
  supports_sms: true
  supports_voice: true
SL:
  country_code: '232'
  name: Sierra Leone
  supports_sms: true
  supports_voice: false
SM:
  country_code: '378'
  name: San Marino
  supports_sms: true
  supports_voice: false
SN:
  country_code: '221'
  name: Senegal
  supports_sms: true
  supports_voice: false
SO:
  country_code: '252'
  name: Somalia
  supports_sms: true
  supports_voice: false
SR:
  country_code: '597'
  name: Suriname
  supports_sms: true
  supports_voice: false
SS:
  country_code: '211'
  name: South Sudan
  supports_sms: true
  supports_voice: false
ST:
  country_code: '239'
  name: São Tomé and Príncipe
  supports_sms: true
  supports_voice: false
SV:
  country_code: '503'
  name: El Salvador
  supports_sms: true
  supports_voice: true
SZ:
  country_code: '268'
  name: Swaziland
  supports_sms: true
  supports_voice: false
TC:
  country_code: '1649'
  name: Turks and Caicos Islands
  supports_sms: true
  supports_voice: false
TD:
  country_code: '235'
  name: Chad
  supports_sms: true
  supports_voice: false
TG:
  country_code: '228'
  name: Togo
  supports_sms: true
  supports_voice: false
TH:
  country_code: '66'
  name: Thailand
  supports_sms: true
  supports_voice: true
TJ:
  country_code: '992'
  name: Tajikistan
  supports_sms: true
  supports_voice: true
TL:
  country_code: '670'
  name: Timor-Leste
  supports_sms: true
  supports_voice: false
TM:
  country_code: '993'
  name: Turkmenistan
  supports_sms: true
  supports_voice: false
TN:
  country_code: '216'
  name: Tunisia
  supports_sms: true
  supports_voice: false
TO:
  country_code: '676'
  name: Tonga
  supports_sms: true
  supports_voice: false
TR:
  country_code: '90'
  name: Turkey
  supports_sms: false
  supports_voice: false
TT:
  country_code: '1868'
  name: Trinidad and Tobago
  supports_sms: true
  supports_voice: true
TV:
  country_code: '688'
  name: Tuvalu
  supports_sms: true
  supports_voice: false
TW:
  country_code: '886'
  name: Taiwan
  supports_sms: true
  supports_voice: true
TZ:
  country_code: '255'
  name: Tanzania
  supports_sms: true
  supports_voice: false
UA:
  country_code: '380'
  name: Ukraine
  supports_sms: true
  supports_voice: false
UG:
  country_code: '256'
  name: Uganda
  supports_sms: true
  supports_voice: false
US:
  country_code: '1'
  name: United States
  supports_sms: true
  supports_voice: true
UY:
  country_code: '598'
  name: Uruguay
  supports_sms: true
  supports_voice: true
UZ:
  country_code: '998'
  name: Uzbekistan
  supports_sms: true
  supports_voice: false
VE:
  country_code: '58'
  name: Venezuela
  supports_sms: true
  supports_voice: true
VG:
  country_code: '1284'
  name: Virgin Islands, British
  supports_sms: true
  supports_voice: false
VI:
  country_code: '1340'
  name: Virgin Islands, US
  supports_sms: true
  supports_voice: false
VN:
  country_code: '84'
  name: Vietnam
  supports_sms: false
  supports_voice: true
VU:
  country_code: '678'
  name: Vanuatu
  supports_sms: true
  supports_voice: false
WS:
  country_code: '685'
  name: Samoa
  supports_sms: true
  supports_voice: false
XK:
  country_code: '383'
  name: Kosovo
  supports_sms: true
  supports_voice: false
YE:
  country_code: '967'
  name: Yemen
  supports_sms: true
  supports_voice: false
YT:
  country_code: '262'
  name: Mayotte
  supports_sms: true
  supports_voice: false
ZA:
  country_code: '27'
  name: South Africa
  supports_sms: true
  supports_voice: true
ZM:
  country_code: '260'
  name: Zambia
  supports_sms: true
  supports_voice: false
ZW:
  country_code: '263'
  name: Zimbabwe
  supports_sms: true
  supports_voice: false
