auth_app_configurations:
  encrypted_otp_secret_key:
    - sensitive

account_reset_requests:
  request_token:
    - sensitive
  granted_token:
    - sensitive

backup_code_configurations:
  salted_code_configuration:
    - sensitive
  code_salt:
    - sensitive

email_addresses:
  confirmation_token:
    - sensitive
  encrypted_email:
    - sensitive

events:
  disavowal_token_fingerprint:
    - sensitive

identities:
  session_uuid:
    - sensitive
  Nonce:
    - sensitive
  access_token:
    - sensitive
  code_challenge:
    - sensitive
  rails_session_id:
    - sensitive

notification_phone_configurations:
  encrypted_phone:
    - sensitive

profiles:
  ssn_signature:
    - sensitive
  name_zip_birth_year_signature:
    - sensitive
  encrypted_pii:
    - sensitive
  encrypted_pii_recovery:
    - sensitive
  encrypted_pii_multi_factor:
    - sensitive
  encrypted_pii_recovery_multi_factor:
    - sensitive

usps_confirmation_codes:
  otp_fingerprint:
    - sensitive

users:
  reset_password_token:
    - sensitive
  direct_otp:
    - sensitive 
  encrypted_password_digest:
    - sensitive
  encrypted_recovery_code_digest:
    - sensitive
  encrypted_password_digest_multi_factor:
    - sensitive
  encrypted_recovery_code_digest_multi_factor:
  - sensitive

service_providers:
  block_encryption:
    - sensitive