disposable_email_services:
  - courtsidemail.com
  - eyamail.com
  - fileright.net
  - immigrationdirect.com
  - kingfishmail.com
  - speedstermail.com
  - sprintpostmail.com
  - usimmigrationemail.com
  - firemailbox.club
  - safemail.icu
  - temp2-login.com
  - temp5-login.com
  - temp9-login.com
  - temp13-login.com
