#!/bin/sh

set -e
set -x

bundle exec rake cf:on_first_instance db:migrate
bundle exec puma --config config/puma.rb

#TEMP
bundle exec sidekiq -q sms -q mailers --config config/sidekiq.yml

bundle exec rspec --require rails_helper
