{{- if and .Values.worker.serviceAccount.create .Values.worker.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity-idp-chart.worker.serviceAccountName" . }}
  labels:
    {{- include "identity-idp-chart.worker.labels" . | nindent 4 }}
  {{- with .Values.worker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}