#!/usr/bin/env ruby

require 'aws-sdk-s3'
require 'yaml'

config = YAML.safe_load(File.read('./.gitlab-ci.yml'), aliases: true)

puts ENV['CI_COMMIT_BRANCH']

bucket = ENV['ARTIFACT_BUCKET']
branch_environments = config.dig(
  'artifact',
  'deploy_branch_to_environment_map',
  ENV['CI_COMMIT_BRANCH'],
)

if bucket && branch_environments
  s3_client = Aws::S3::Client.new(region: region)
  branch_environments.map do |upload_environment|
    s3_client.put_object(
      bucket: bucket,
      key: "#{upload_environment}/#{`git rev-parse HEAD`.chomp}.idp.tar.gz",
      body: File.read(ARGV[0]),
    )
  end
end
