#!/usr/bin/env ruby

require 'yaml'
require 'open3'

config = YAML.safe_load(File.read('./.gitlab-ci-deploy.yml'))

artifact_bucket = ENV['ARTIFACT_BUCKET']
_region = ENV.fetch('AWS_REGION')
sha = ENV.fetch('CI_COMMIT_SHA')

branch_environments = config.dig(
  'deploy_branch_to_environment_map',
  ENV.fetch('CI_COMMIT_BRANCH'),
)

branch_environments.map do |upload_environment|
  static_bucket = ENV["#{upload_environment.upcase}_STATIC_BUCKET"]

  if static_bucket.nil?
    puts "skipping #{upload environment} because it is missing static bucket config!"
    next
  end

  key = "#{upload_environment}/#{sha}.idp.tar.gz"
  puts "uploading #{key}!"
  s3_artifact_uri = "s3://#{artifact_bucket}/#{key}"

  Open3.capture2(
    'aws', 's3', 'cp', ARGV[0], s3_artifact_uri
  )

  assets_sync_command = <<-CMD
    aws s3 sync --size-only --cache-control max-age=31536000 --exclude .sprockets-manifest-*.json public/assets s3://#{static_bucket}/assets
  CMD
  Open3.capture2(assets_sync_command)

  packs_sync_command = <<-CMD
    aws s3 sync --size-only --cache-control max-age=31536000 --exclude "manifest.json" public/packs s3://#{static_bucket}/packs
  CMD
  Open3.capture2(packs_sync_command)

  manifest_sync_command = <<-CMD
    aws s3 cp public/packs/manifest.json s3://#{static_bucket}/packs/manifest.json
  CMD
  Open3.capture2(manifest_sync_command)
end
