#!/bin/bash -euo pipefail

: ${GZIP_COMMAND:=gzip}


# ARTIFACT_DIRECTORY is the source directory containing the IDP repository that is being
# turned into a file artifact
bundle config set --local cache_all true
bundle package
tar \
  --exclude './config/agencies.yml' \
  --exclude './config/iaa_gtcs.yml' \
  --exclude './config/iaa_orders.yml' \
  --exclude './config/iaa_statuses.yml' \
  --exclude './config/integration_statuses.yml' \
  --exclude './config/integrations.yml' \
  --exclude './config/partner_account_statuses.yml' \
  --exclude './config/partner_accounts.yml' \
  --exclude './config/service_providers.yml' \
  --exclude='./certs/sp' \
  --exclude='./identity-idp-config' \
  --exclude='./tmp' \
  --exclude='./node_modules' \
  --exclude='./geo_data/GeoLite2-City.mmdb' \
  --exclude='./pwned_passwords/pwned_passwords.txt' \
  --exclude='./vendor/ruby' \
  --exclude='./config/application.yml' \
  -cf - "$ARTIFACT_DIRECTORY" | "$GZIP_COMMAND" > "$ARTIFACT_DESTINATION_FILE"
