#!/bin/bash

if [ -d './db/migrate' ]
then
	echo "The ./db/migrate folder should not be used for generating migrations"
	echo "Use the --database option to specify the database to be used. Example:"
	echo "rails g migration add_my_database_table --database primary"
	exit 1
fi
