#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path('../lib', File.dirname(__FILE__)))
require 'pinpoint_supported_countries'
require 'yaml'

puts YAML.dump(PinpointSupportedCountries.new.run)
