#!/usr/bin/env ruby
# frozen_string_literal: true

require 'yaml'
require 'nokogiri'

if ARGV.empty?
  raise 'Pass YAML files as arguments. Example: `scripts/yaml_characters path/to/example.yml`'
end

def sanitize(string)
  Nokogiri::HTML5(string).content.gsub(/%{.+?}/, '').gsub(/[\n\r]/, '')
end

def hash_values(hash, all_values: [])
  hash.each do |key, value|
    if value.is_a?(Hash)
      hash_values(value, all_values:)
    elsif value.is_a?(Array)
      value.each { |item| all_values << item }
    else
      all_values << value
    end
  end

  all_values
end

characters = ARGV.flat_map do |file|
  strings = hash_values(YAML.load_file(file))
  joined_string = strings.join('')
  sanitized_string = sanitize(joined_string)
  sanitized_string.chars.to_a
end.uniq.sort.join('')

STDOUT.puts characters
