#!/bin/bash
set -xeuo pipefail

# Script to help fix merge conflicts when migrating to the flat yml style
# Run it after doing a `git merge origin/main` into a feature branch

# Intended to be a temporary script only for flat yml migration

# git checkout origin/main -- config/locales/

locales=("en" "es" "fr" "zh")

function find_locale_files() {
  locale=$1

  find config/locales -type f -name "*${locale}.yml" | \
    grep -v telephony | \
    grep -v transliterate
}

for locale in $locales; do
  find_locale_files "$locale" |
    xargs ./scripts/yml_to_flat_yml > "tmp/newer_${locale}.yml"

  if [ -f "config/locales/${locale}.yml" ]; then
    cp "config/locales/${locale}.yml" "tmp/older_${locale}.yml"
  else
    echo > "tmp/older_${locale}.yml"
  fi

  ./scripts/merge_yml \
    "tmp/older_${locale}.yml" \
    "tmp/newer_${locale}.yml" \
    > "config/locales/${locale}.yml"
done

if [[ "${1:-}" == "--force" ]]; then
  git status --porcelain | grep "DU " | cut -d' ' -f 2 | xargs git rm

  for locale in $locales; do
    find_locale_files "$locale" | \
      grep -v "config/locales/${locale}.yml" | \
      xargs git rm -f
  done
fi

make normalize_yaml

for locale in $locales; do
  git add "config/locales/${locale}.yml"
done
