get:
  tags:
    - StreamManagement
  summary: Transmitter Configuration Request (without path)
  description: "Return Transmitter Configuration information."
  operationId: _well_known_ssf_configuration_get
  security: [ ]
  responses:
    200:
      description: |
        A set of Claims about the Transmitter's configuration,
        including all necessary endpoints and public key location information
      content:
        application/json:
          schema:
             $ref: "../schemas/TransmitterConfiguration.yml"
    400:
      description: |
        The 400 (Bad Request) status code indicates that the server cannot or
        will not process the request due to something that is perceived to be
        a client error (e.g., malformed request syntax, invalid request
        message framing, or deceptive request routing).
    "5XX":
      description: Unexpected error.