---
name: jwt
version: '2.5'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: f2fa96be08e0f7fe5237a45d2b69d9d7a5d0b416
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
