# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Idv::AccountVerifiedEmailPresenter`.
# Please instead update this file by running `bin/tapioca dsl Idv::AccountVerifiedEmailPresenter`.


class Idv::AccountVerifiedEmailPresenter
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
