#!/usr/bin/env bash
# Self-check for the delegated-access skill. Run from the repository root. Exits non-zero on the
# first failure. Replaces a test in the repository's suite so CI is not slowed down; the skill runs
# this at every invocation (via build_index.py --check) and after every change to docs/ or the skill.
set -euo pipefail

skill=".claude/skills/login-delegated-access"
twin=".agents/skills"
fail() { echo "check: FAIL: $*" >&2; exit 1; }

# 1. Generated references and document matrices are current.
python3 "$skill/scripts/build_index.py" --check || fail "generated references or document matrices are stale; run build_index.py"

# 2. Twins are byte-identical (same file set, same content).
bash "$skill/scripts/sync_twins.sh" --check || fail "twins differ; run sync_twins.sh"

# 3. Every generated reference carries its generation header.
for f in requirements-index.md traceability.md branches.md decisions.md; do
  head -1 "$skill/references/$f" | grep -q '^<!-- generated by ' || fail "$f lacks the generation header"
done

# 4. Each document has exactly one traceability marker pair.
for d in docs/delegated-access-implementation-plan.md docs/delegated-access-functional-requirements.md docs/delegated-access-requirements.md; do
  b=$(grep -c '<!-- traceability:begin -->' "$d"); e=$(grep -c '<!-- traceability:end -->' "$d")
  [ "$b" = 1 ] && [ "$e" = 1 ] || fail "$d has $b begin / $e end markers (expected 1 / 1)"
done

# 5. The central skill file stays within its size limit.
lines=$(wc -l < "$skill/SKILL.md")
[ "$lines" -le 150 ] || fail "SKILL.md is $lines lines (limit 150)"

echo "check: OK (generated references current, twins identical, headers present, markers paired, SKILL.md $lines lines)"
