# Seeds data into database on first install
{{- if and .Values.idp.enabled .Values.idp.hooks.seed }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "identity-idp-chart.idp.fullname" . }}-seed-database
  labels:
    {{- include "identity-idp-chart.idp.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.idp.hooks.annotations | nindent 4 }}
spec:
  backoffLimit: {{ .Values.idp.hooks.backoffLimit }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "identity-idp-chart.idp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.idp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "identity-idp-chart.idp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.idp.podSecurityContext | nindent 8 }}
      restartPolicy: OnFailure
      containers:
        - name: {{ include "identity-idp-chart.fullname" . }}-seed-database
          securityContext:
            {{- toYaml .Values.idp.securityContext | nindent 12 }}
          image: "{{ .Values.idp.image.repository }}:{{ .Values.idp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.idp.image.pullPolicy }}
          env:
            {{- toYaml .Values.idp.env | nindent 12 }}
          command: [ bundle ]
          args: 
            - exec
            - rake
            - db:seed
          resources:
            {{- toYaml .Values.idp.resources | nindent 12 }}
  backoffLimit: 4
{{- end }}
