{{- if and .Values.idp.serviceAccount.create .Values.idp.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity-idp-chart.idp.serviceAccountName" . }}
  labels:
    {{- include "identity-idp-chart.idp.labels" . | nindent 4 }}
  {{- with .Values.idp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
