{{- if .Values.idp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity-idp-chart.idp.fullname" . }}
  labels:
    {{- include "identity-idp-chart.idp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.idp.service.type }}
  ports:
    - port: {{ .Values.idp.service.port }}
      targetPort: {{ .Values.idp.service.port }}
      protocol: TCP
      name: https
  selector:
    {{- include "identity-idp-chart.idp.selectorLabels" . | nindent 4 }}
{{- end }}
