name: Create deploy PR
on:
  workflow_dispatch:
    inputs:
      deploy_type:
        description: 'Type of deploy'
        required: true
        type: choice
        options:
          - Normal
          - Patch
      source:
        description: 'Source branch/SHA (If blank, the current SHA running on staging will be used)'
        required: false
        type: string
permissions:
  pull-requests: write
  contents: write
jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      PATCH: ${{ inputs.deploy_type == 'Patch' && 1 || 0 }}
      SOURCE: ${{ inputs.source }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get all commits
      - uses: ruby/setup-ruby@v1
      - run: scripts/create-deploy-pr
