name: Create release
on:
  pull_request:
    types:
      - closed
    branches:
      - 'stages/prod'
jobs:
  create-release:
    name: Create release after PR merge
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - run: scripts/create-release ${{ github.event.pull_request.number }}