{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "identity-idp-chart.postgres.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "identity-idp-chart.postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "identity-idp-chart.postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "identity-idp-chart.postgres.fullname" . }}
        image: {{ .Values.postgresql.image }}:{{ .Values.postgresql.tag }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresql.password }}
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.database }}
        ports:
        - containerPort: {{ .Values.postgresql.service.port }}
        volumeMounts:
        - name: {{ include "identity-idp-chart.postgres.fullname" . }}-data
          mountPath: /var/lib/postgresql/data
      volumes:
      {{- if .Values.postgresql.persistence.enabled }}
      - name: {{ include "identity-idp-chart.postgres.fullname" . }}-data
        persistentVolumeClaim:
          claimName: {{ include "identity-idp-chart.postgres.fullname" . }}-pvc
      {{- else }}
      - name: {{ include "identity-idp-chart.postgres.fullname" . }}-data
        emptyDir: {}
      {{- end }}
{{- end }}
